// examples/nextjs-app-router/app/page.tsx
// Copyright © 2024 Ory Corp
// SPDX-License-Identifier: Apache-2.0

"use client"
import Link from "next/link"
import { useSession } from "@ory/elements-react/client"

export default function RootLayout() {
  const { session } = useSession()
  if (session) {
    return "Hello: " + session.identity?.traits.email
  }
  return (
    <p>
      Not authenticated, please <Link href={"/auth/login"}>log in</Link>.
    </p>
  )
}

// examples/nuxt-app/app.vue
<!-- Copyright © 2026 Ory Corp -->
<!-- SPDX-License-Identifier: Apache-2.0 -->

<script setup lang="ts">
import { SessionProvider } from "@ory/elements-vue/client"

// Get session from server for hydration
const { data: sessionResult } = await useOrySession()
const initialSession = computed(() => sessionResult.value?.session ?? null)
</script>

<template>
  <SessionProvider :session="initialSession">
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
  </SessionProvider>
</template>
