// examples/nuxt-app/pages/verification.vue
<!-- Copyright © 2026 Ory Corp -->
<!-- SPDX-License-Identifier: Apache-2.0 -->

<script setup lang="ts">
import { Verification } from "@ory/elements-vue"

useHead({ title: "Verification" })

definePageMeta({
  layout: "auth",
})

const config = useOryConfig()
const flow = await useOryVerificationFlow()
</script>

<template>
  <div>
    <Verification v-if="flow" :flow="flow" :config="config" />
    <div v-else class="text-center">
      <p class="text-gray-500">Loading...</p>
    </div>
  </div>
</template>

// examples/nextjs-pages-router/pages/auth/verification.tsx
// Copyright © 2024 Ory Corp
// SPDX-License-Identifier: Apache-2.0
"use client"
import { Verification } from "@ory/elements-react/theme"
import { useVerificationFlow } from "@ory/nextjs/pages"
import { enhanceOryConfig } from "@ory/nextjs"
import "@ory/elements-react/theme/styles.css"

import config from "@/ory.config"

export default function VerificationPage() {
  const flow = useVerificationFlow()

  if (!flow) {
    return null
  }

  return (
    <div className="pt-4">
      <Verification
        flow={flow}
        config={enhanceOryConfig(config)}
        components={{
          Card: {},
        }}
      />
    </div>
  )
}
