// examples/nuxt-app/pages/index.vue
<!-- Copyright © 2026 Ory Corp -->
<!-- SPDX-License-Identifier: Apache-2.0 -->

<script setup lang="ts">
import { useSession } from "@ory/elements-vue/client"

useHead({ title: "Home" })

// Use client-side session from SessionProvider
const { session, isLoading } = useSession()
const { data: logoutFlow } = await useOryLogout()

const traits = computed(() => {
  return session.value?.identity?.traits as
    | {
        email?: string
        username?: string
        phone?: string
      }
    | undefined
})

const displayName = computed(() => {
  return traits.value?.email ?? traits.value?.username ?? traits.value?.phone
})
</script>

<template>
  <div class="flex items-center justify-center min-h-screen bg-gray-50">
    <div class="flex flex-col items-center gap-4">
      <img src="/ory-logo.svg" alt="Ory Logo" width="160" />
      <h1 class="font-bold text-xl">Ory Nuxt Example</h1>

      <div
        v-if="!session"
        class="flex items-center gap-2 bg-white rounded-sm border flex-col w-60 p-3"
      >
        <NuxtLink class="underline block w-full" to="/registration">
          Registration
        </NuxtLink>
        <NuxtLink class="underline block w-full" to="/login"> Login </NuxtLink>
        <NuxtLink class="underline block w-full" to="/recovery">
          Account Recovery
        </NuxtLink>
        <NuxtLink class="underline block w-full" to="/verification">
          Account Verification
        </NuxtLink>
      </div>

      <div
        v-else
        class="flex items-center gap-2 bg-white rounded-sm border flex-col w-60 p-3"
      >
        <h2 class="w-full">Hi, {{ displayName }}!</h2>
        <NuxtLink class="underline block w-full" to="/settings">
          Settings
        </NuxtLink>
        <a
          v-if="logoutFlow?.logout_url"
          class="underline block w-full"
          :href="logoutFlow.logout_url"
        >
          Logout
        </a>
      </div>

      <div class="flex gap-2 text-sm">
        <a
          href="https://github.com/ory/elements/tree/master/examples/nuxt-app"
          class="underline"
          target="_blank"
          rel="noreferrer"
        >
          Nuxt Example
        </a>
        <a
          href="https://github.com/ory/elements/tree/master/examples/nextjs-app-router"
          class="underline"
          target="_blank"
          rel="noreferrer"
        >
          Next.js Example
        </a>
      </div>
    </div>
  </div>
</template>

// examples/nextjs-pages-router/pages/index.tsx
// Copyright © 2024 Ory Corp
// SPDX-License-Identifier: Apache-2.0

import React from "react"
import Link from "next/link"
import { SessionProvider, useSession } from "@ory/elements-react/client"
import Image from "next/image"
import OryLogo from "./logo.svg"
import { useLogoutFlow } from "@ory/nextjs/pages"

function HomeContent() {
  const { session } = useSession()

  return (
    <div className="flex items-center justify-center min-h-screen bg-gray-50">
      <div className="flex flex-col items-center gap-4">
        <Image src={OryLogo} alt="Ory Logo" width={160} />
        <h1 className="font-bold text-xl">Ory Next.js App Router Example</h1>
        {!session && (
          <div className="flex items-center gap-2 bg-white rounded border flex-col w-60 p-3">
            <Link className="underline block w-full" href="/auth/registration">
              Registration
            </Link>
            <Link className="underline block w-full" href="/auth/login">
              Login
            </Link>
            <Link className="underline block w-full" href="/auth/recovery">
              Account Recovery
            </Link>
            <Link className="underline block w-full" href="/auth/verification">
              Account Verification
            </Link>
          </div>
        )}
        {session && (
          <div className="flex items-center gap-2 bg-white rounded border flex-col w-60 p-3">
            <h2 className="w-full">
              Hi,{" "}
              {session.identity?.traits.email ??
                session.identity?.traits.username ??
                session.identity?.traits.phone}
              !
            </h2>
            <Link className="underline block w-full" href="/settings">
              Settings
            </Link>
            <LogoutLink />
          </div>
        )}
        <div className="flex gap-2 text-sm">
          <a
            href="https://github.com/ory/elements/tree/master/examples/nextjs-pages-router"
            className="underline"
            target="_blank"
            rel="noreferrer"
          >
            App Router Example
          </a>
          <a
            href="https://github.com/ory/elements/tree/master/examples/nextjs-pages-router"
            className="underline"
            target="_blank"
            rel="noreferrer"
          >
            Page Router Example
          </a>
        </div>
      </div>
    </div>
  )
}

function LogoutLink() {
  const flow = useLogoutFlow()

  if (!flow) {
    return null
  }

  return (
    <a className="underline block w-full" href={flow.logout_url}>
      Logout
    </a>
  )
}

export default function Home() {
  return (
    <SessionProvider>
      <HomeContent />
    </SessionProvider>
  )
}
