// packages/elements-react/src/theme/default/flows/consent.tsx
// Copyright © 2025 Ory Corp
// SPDX-License-Identifier: Apache-2.0

import { FlowType, OAuth2ConsentRequest, Session } from "@ory/client-fetch"
import {
  OryClientConfiguration,
  OryConsentCard,
  OryFlowComponentOverrides,
  OryProvider,
} from "@ory/elements-react"
import { PropsWithChildren } from "react"
import { getOryComponents } from "../components"
import { translateConsentChallengeToUiNodes } from "../utils/oauth2"

type PropsWithComponents = {
  components?: OryFlowComponentOverrides
}

export type ConsentFlowContextProps = {
  consentChallenge: OAuth2ConsentRequest
  session: Session
  config: OryClientConfiguration
  csrfToken: string
  formActionUrl: string
} & PropsWithComponents

export function Consent({
  consentChallenge,
  session,
  config,
  components: Passed,
  children,
  csrfToken,
  formActionUrl,
}: PropsWithChildren<ConsentFlowContextProps>) {
  const components = getOryComponents(Passed)

  const flow = translateConsentChallengeToUiNodes(
    consentChallenge,
    csrfToken,
    formActionUrl,
    session,
  )

  return (
    <OryProvider
      config={config}
      flow={flow}
      flowType={FlowType.OAuth2Consent}
      components={components}
    >
      {children ?? <OryConsentCard />}
    </OryProvider>
  )
}

// packages/elements-vue/src/theme/default/flows/Consent.vue
<!-- Copyright © 2026 Ory Corp -->
<!-- SPDX-License-Identifier: Apache-2.0 -->

<script setup lang="ts">
import type { OAuth2ConsentRequest, Session } from "@ory/client-fetch"
import { FlowType } from "@ory/client-fetch"
import { OryProvider, OryConsentCard } from "../../../components"
import { getOryComponents } from "../getOryComponents"
import { translateConsentChallengeToUiNodes } from "../utils/oauth2"
import type { OryClientConfiguration } from "../../../composables/useOryConfig"
import type { OryFlowComponentOverrides } from "../../../composables/useComponents"
import type { ConsentFlowContainer } from "../../../util/flowContainer"

const props = defineProps<{
  consentChallenge: OAuth2ConsentRequest
  session: Session
  config: OryClientConfiguration
  csrfToken: string
  formActionUrl: string
  components?: OryFlowComponentOverrides
}>()

const components = getOryComponents(props.components)
const flow = translateConsentChallengeToUiNodes(
  props.consentChallenge,
  props.csrfToken,
  props.formActionUrl,
  props.session,
)
const flowContainer: ConsentFlowContainer = {
  flow,
  flowType: FlowType.OAuth2Consent,
}
</script>

<template>
  <OryProvider
    :flow-container="flowContainer"
    :config="config"
    :components="components"
  >
    <slot>
      <OryConsentCard />
    </slot>
  </OryProvider>
</template>
