// packages/elements-vue/src/theme/default/flows/Recovery.vue
<!-- Copyright © 2026 Ory Corp -->
<!-- SPDX-License-Identifier: Apache-2.0 -->

<script setup lang="ts">
import type { RecoveryFlow } from "@ory/client-fetch"
import { FlowType } from "@ory/client-fetch"
import { OryProvider, OrySelfServiceFlowCard } from "../../../components"
import { getOryComponents } from "../getOryComponents"
import type { OryClientConfiguration } from "../../../composables/useOryConfig"
import type { OryFlowComponentOverrides } from "../../../composables/useComponents"
import type { RecoveryFlowContainer } from "../../../util/flowContainer"

const props = defineProps<{
  flow: RecoveryFlow
  components?: OryFlowComponentOverrides
  config: OryClientConfiguration
}>()

const components = getOryComponents(props.components)
const flowContainer: RecoveryFlowContainer = {
  flow: props.flow,
  flowType: FlowType.Recovery,
}
</script>

<template>
  <OryProvider
    :flow-container="flowContainer"
    :config="config"
    :components="components"
  >
    <slot>
      <OrySelfServiceFlowCard />
    </slot>
  </OryProvider>
</template>

// packages/elements-react/src/theme/default/flows/recovery.tsx
// Copyright © 2024 Ory Corp
// SPDX-License-Identifier: Apache-2.0

"use client"
import { FlowType, RecoveryFlow } from "@ory/client-fetch"
import {
  OryClientConfiguration,
  OryFlowComponentOverrides,
  OryProvider,
  OryTwoStepCard,
} from "@ory/elements-react"
import { PropsWithChildren } from "react"
import { getOryComponents } from "../components"

export type RecoveryFlowContextProps = {
  flow: RecoveryFlow
  components?: OryFlowComponentOverrides
  config: OryClientConfiguration
}

export function Recovery({
  flow,
  config,
  children,
  components: flowOverrideComponents,
}: PropsWithChildren<RecoveryFlowContextProps>) {
  const components = getOryComponents(flowOverrideComponents)
  return (
    <OryProvider
      config={config}
      flow={flow}
      flowType={FlowType.Recovery}
      components={components}
    >
      {children ?? <OryTwoStepCard />}
    </OryProvider>
  )
}
