// packages/elements-vue/src/theme/default/flows/Settings.vue
<!-- Copyright © 2026 Ory Corp -->
<!-- SPDX-License-Identifier: Apache-2.0 -->

<script setup lang="ts">
import type { SettingsFlow, Session } from "@ory/client-fetch"
import { FlowType } from "@ory/client-fetch"
import {
  OryProvider,
  OrySettingsCard,
  OryPageHeader,
} from "../../../components"
import { getOryComponents } from "../getOryComponents"
import type { OryClientConfiguration } from "../../../composables/useOryConfig"
import type { OryFlowComponentOverrides } from "../../../composables/useComponents"
import type { SettingsFlowContainer } from "../../../util/flowContainer"
import { provideSession } from "../../../client/useSession"

const props = withDefaults(
  defineProps<{
    flow: SettingsFlow
    components?: OryFlowComponentOverrides
    config: OryClientConfiguration
    className?: string
    session?: Session | null
  }>(),
  {
    session: null,
  },
)

const components = getOryComponents(props.components)
const flowContainer: SettingsFlowContainer = {
  flow: props.flow,
  flowType: FlowType.Settings,
}

provideSession({ session: props.session, baseUrl: props.config.sdk?.url })
</script>

<template>
  <OryProvider
    :flow-container="flowContainer"
    :config="config"
    :components="components"
  >
    <slot>
      <div :class="['ory-elements', className]">
        <div
          class="flex flex-col items-center justify-start gap-8 pb-12 font-sans-default"
        >
          <OryPageHeader />
          <OrySettingsCard />
        </div>
      </div>
    </slot>
  </OryProvider>
</template>

// packages/elements-react/src/theme/default/flows/settings.tsx
// Copyright © 2024 Ory Corp
// SPDX-License-Identifier: Apache-2.0

"use client"
import { FlowType, SettingsFlow } from "@ory/client-fetch"
import {
  OryClientConfiguration,
  OryFlowComponentOverrides,
  OryProvider,
  OrySettingsCard,
} from "@ory/elements-react"
import merge from "lodash.merge"
import { PropsWithChildren } from "react"
import { OryDefaultComponents } from "../components"

export type SettingsFlowContextProps = {
  flow: SettingsFlow
  components?: OryFlowComponentOverrides
  config: OryClientConfiguration
}

export function Settings({
  flow,
  config,
  children,
  components: flowOverrideComponents,
}: PropsWithChildren<SettingsFlowContextProps>) {
  const components = flowOverrideComponents
    ? merge({}, OryDefaultComponents, flowOverrideComponents)
    : OryDefaultComponents
  return (
    <OryProvider
      config={config}
      flow={flow}
      flowType={FlowType.Settings}
      components={components}
    >
      {children ?? <OrySettingsCard />}
    </OryProvider>
  )
}
