// packages/elements-vue/src/theme/default/flows/Registration.vue
<!-- Copyright © 2026 Ory Corp -->
<!-- SPDX-License-Identifier: Apache-2.0 -->

<script setup lang="ts">
import type { RegistrationFlow } from "@ory/client-fetch"
import { FlowType } from "@ory/client-fetch"
import { OryProvider, OrySelfServiceFlowCard } from "../../../components"
import { getOryComponents } from "../getOryComponents"
import type { OryClientConfiguration } from "../../../composables/useOryConfig"
import type { OryFlowComponentOverrides } from "../../../composables/useComponents"
import type { RegistrationFlowContainer } from "../../../util/flowContainer"

const props = defineProps<{
  flow: RegistrationFlow
  components?: OryFlowComponentOverrides
  config: OryClientConfiguration
}>()

const components = getOryComponents(props.components)
const flowContainer: RegistrationFlowContainer = {
  flow: props.flow,
  flowType: FlowType.Registration,
}
</script>

<template>
  <OryProvider
    :flow-container="flowContainer"
    :config="config"
    :components="components"
  >
    <slot>
      <OrySelfServiceFlowCard />
    </slot>
  </OryProvider>
</template>

// packages/elements-react-stories/src/elements-react/pages/registration.tsx
// Copyright © 2024 Ory Corp
// SPDX-License-Identifier: Apache-2.0

"use client"

import { Configuration, FlowType, RegistrationFlow } from "@ory/client-fetch"
import {
  OryCard,
  OryClientConfiguration,
  OryFlowComponents,
  OryProvider,
} from "@ory/elements-react"
import { OryDefaultComponents } from "@ory/elements-react/theme"
import { PropsWithChildren } from "react"

export type FlowContextProps = {
  flow: RegistrationFlow
  components?: Partial<OryFlowComponents>
  config: OryClientConfiguration
}

export function Registration({
  flow,
  config,
  children,
  components,
}: PropsWithChildren<FlowContextProps>) {
  return (
    <OryProvider
      config={config}
      flow={flow}
      flowType={FlowType.Registration}
      components={{ ...OryDefaultComponents, ...components }}
    >
      {children || <OryCard />}
    </OryProvider>
  )
}
