// examples/nextjs-pages-router/pages/auth/recovery.tsx
// Copyright © 2024 Ory Corp
// SPDX-License-Identifier: Apache-2.0
"use client"
import { Recovery } from "@ory/elements-react/theme"
import { useRecoveryFlow } from "@ory/nextjs/pages"
import { enhanceConfig } from "@ory/nextjs"
import "@ory/elements-react/theme/styles.css"

import config from "@/ory.config"

export default function RecoveryPage() {
  const flow = useRecoveryFlow()

  if (!flow) {
    return null
  }

  return (
    <div className="pt-4">
      <Recovery
        flow={flow}
        config={enhanceConfig(config)}
        components={{
          Card: {},
        }}
      />
    </div>
  )
}

// examples/nuxt-app/pages/recovery.vue
<!-- Copyright © 2026 Ory Corp -->
<!-- SPDX-License-Identifier: Apache-2.0 -->

<script setup lang="ts">
import { Recovery } from "@ory/elements-vue"

useHead({ title: "Recovery" })

definePageMeta({
  layout: "auth",
})

const config = useOryConfig()
const flow = await useOryRecoveryFlow()
</script>

<template>
  <div>
    <Recovery v-if="flow" :flow="flow" :config="config" />
    <div v-else class="text-center">
      <p class="text-gray-500">Loading...</p>
    </div>
  </div>
</template>
