// examples/nextjs-pages-router/pages/settings.tsx
// Copyright © 2024 Ory Corp
// SPDX-License-Identifier: Apache-2.0

import config from "@/ory.config"
import { Settings } from "@ory/elements-react/theme"
import { useSettingsFlow } from "@ory/nextjs/pages"
import { SessionProvider } from "../../../packages/elements-react/dist/client/session-provider"

export default function SettingsPage() {
  const flow = useSettingsFlow()

  if (!flow) {
    return null
  }

  return (
    <div className="flex flex-col gap-8 items-center mb-8">
      <SessionProvider>
        <Settings
          flow={flow}
          config={config}
          components={{
            Card: {},
          }}
        />
      </SessionProvider>
    </div>
  )
}

// examples/nuxt-app/pages/settings.vue
<!-- Copyright © 2026 Ory Corp -->
<!-- SPDX-License-Identifier: Apache-2.0 -->

<script setup lang="ts">
import { Settings } from "@ory/elements-vue"

useHead({ title: "Settings" })

definePageMeta({
  middleware: "auth",
})

const config = useOryConfig()
const flow = await useOrySettingsFlow()
const { data: sessionResult } = await useOrySession()
</script>

<template>
  <div class="flex flex-col gap-8 items-center mb-8">
    <Settings
      v-if="flow"
      :flow="flow"
      :config="config"
      :session="sessionResult?.session"
    />
    <div v-else class="text-center py-12">
      <p class="text-gray-500">Loading...</p>
    </div>
  </div>
</template>
