// examples/nextjs-app-router/app/auth/verification/page.tsx
// Copyright © 2024 Ory Corp
// SPDX-License-Identifier: Apache-2.0

import CustomCardHeader from "@/components/custom-card-header"
import { Verification } from "@ory/elements-react/theme"
import { getVerificationFlow, OryPageParams } from "@ory/nextjs/app"

import config from "@/ory.config"

export default async function VerificationPage(props: OryPageParams) {
  const flow = await getVerificationFlow(config, props.searchParams)

  if (!flow) {
    return null
  }

  return (
    <Verification
      flow={flow}
      config={config}
      components={{
        Card: {
          Header: CustomCardHeader,
        },
      }}
    />
  )
}

// examples/nuxt-app/pages/verification.vue
<!-- Copyright © 2026 Ory Corp -->
<!-- SPDX-License-Identifier: Apache-2.0 -->

<script setup lang="ts">
import { Verification } from "@ory/elements-vue"

useHead({ title: "Verification" })

definePageMeta({
  layout: "auth",
})

const config = useOryConfig()
const flow = await useOryVerificationFlow()
</script>

<template>
  <div>
    <Verification v-if="flow" :flow="flow" :config="config" />
    <div v-else class="text-center">
      <p class="text-gray-500">Loading...</p>
    </div>
  </div>
</template>
